import java.util.Random;
import java.util.Scanner;

public class Games {

    //PRE:  accepts scanner from main
    //POST: asks the user for a 2 digit # & compares the
    //      value to one generated by computer
    //      evaluates whether the user 'won' the lottery
   
    public static void lotteryGame(Scanner input) {
        System.out.println("\nWELCOME TO THE LOTTERY!!\n");

        // Create random number generator and scanner
        Random rand = new Random();

        // Step 1: Generate a random two-digit lottery number (10 to 99)
        //         && set the 2 digits of lottery number 

        // Step 2: Prompt the user to enter a two-digit number
 

        // Step 3:Ensure it's a valid two-digit number
 
        // Step 4: get the 2 digits of userGuess

        // Step 5: Display lottery number
 

        // Step 6: Check for types of matches & print results
        // exact match
 
        // Step 7: Check for all digits match (in different order)
 
        // Step 8: Check for one digit match
 
        // Step 9: No match
 

    }

    //PRE:  accepts scanner from main
    //POST: while the user chooses to play:
    //      the user will place their bet & roll dice
    //      the game will determine the outcome and update the bet
    //      the user cannot play anymore if they are out of money

    public static void playCraps(Scanner input) {
        System.out.println("\nWELCOME TO CRAPS!!\n");




        System.out.println("Thanks for playing!");

    }

}
 

